Repository La-Fresca/la-fresca-frontend, pull requests merged in 2024-11, with the labels that each got.

#120 fix: view branches - top level manager
  package-lock.json
  package.json
  src/components/TopLevelManager/BranchDropdown/index.tsx
  src/components/TopLevelManager/Header/DropdownUser.tsx
  src/components/TopLevelManager/Tables/Branches/GrnList.tsx
  src/components/TopLevelManager/Tables/Branches/GrnListbyCollection.tsx
  src/components/TopLevelManager/Tables/Branches/InventoryList.tsx
  src/components/TopLevelManager/Tables/Branches/columnInventory.ts
  src/components/TopLevelManager/Tables/Branches/columnStocks.ts
  src/components/TopLevelManager/Tables/Branches/stock/ChevronDownIcon.tsx
  src/components/TopLevelManager/Tables/Branches/stock/PlusIcon.tsx
  src/components/TopLevelManager/Tables/Branches/stock/SearchIcon.tsx
  src/components/TopLevelManager/Tables/Branches/stock/VerticalDotsIcon.tsx
  src/components/TopLevelManager/Tables/Branches/stock/data.tsx
  src/components/TopLevelManager/Tables/Branches/stockCollection/ChevronDownIcon.tsx
  src/components/TopLevelManager/Tables/Branches/stockCollection/PlusIcon.tsx
  src/components/TopLevelManager/Tables/Branches/stockCollection/SearchIcon.tsx
  src/components/TopLevelManager/Tables/Branches/stockCollection/VerticalDotsIcon.tsx
  src/components/TopLevelManager/Tables/Branches/stockCollection/data.tsx
  src/components/TopLevelManager/Tables/Branches/utils.ts
  src/components/User/Header/DropdownUser.tsx
  src/pages/TopLevelManager/Branches/BranchList.tsx
Labels: feat

#125 update
  src/components/User/ContactUs/index.tsx
  src/components/User/Discount/index.tsx
Labels: fix

#123 Order history responsive and light mode
  src/App.tsx
  src/components/Gallery/Gallery.tsx
  src/components/Landing/Gallery.tsx
  src/components/User/OrderHistory/OrderCard.tsx
  src/components/User/OrderHistory/OrderDetails.tsx
  src/components/User/OrderHistory/OrderHistory.tsx
  src/components/User/OrderHistory/OrderHistoryDetails.tsx
  src/components/User/OrderHistory/OrderItem.tsx
  src/pages/Home/index.tsx
Labels: bug

#126 Fix: Food item functionality - top level manager
  src/App.tsx
  src/api/useBranches.tsx
  src/api/useFoods.tsx
  src/components/TopLevelManager/DynamicForms/AddBranch.tsx
  src/components/TopLevelManager/Tables/FoodItems/Components/ChevronDownIcon.tsx
  src/components/TopLevelManager/Tables/FoodItems/Components/PlusIcon.tsx
  src/components/TopLevelManager/Tables/FoodItems/Components/SearchIcon.tsx
  src/components/TopLevelManager/Tables/FoodItems/Components/VerticalDotsIcon.tsx
  src/components/TopLevelManager/Tables/FoodItems/Components/data.tsx
  src/components/TopLevelManager/Tables/FoodItems/Components/types.tsx
  src/components/TopLevelManager/Tables/FoodItems/FoodItemList.tsx
  src/components/TopLevelManager/Tables/FoodItems/utils.ts
  src/components/UI/SwalConfirm.tsx
  src/images/footer/FB.svg
  src/images/footer/IG.svg
  src/images/footer/X.svg
  src/images/footer/footer.jpg
  src/images/footer/footer2.webp
  src/images/footer/footer3.png
  src/images/footer/footer4.jpeg
  src/images/icon/check.png
  src/images/icon/check.svg
  src/images/icon/cross.png
  src/images/icon/cross1.png
  src/images/icon/cross2.png
  src/pages/Home/index.tsx
  src/pages/TopLevelManager/Foods/AddFood.tsx
  src/pages/TopLevelManager/Foods/EditFood.tsx
  src/pages/TopLevelManager/Foods/index.tsx
  src/types/food.ts
  src/types/user.ts
Labels: fix

#128 View food items - top level manager
  src/api/useBranches.tsx
  src/api/useFoods.tsx
  src/components/TopLevelManager/BranchDropdown/index.tsx
  src/components/TopLevelManager/Tables/Branches/BranchList.tsx
  src/components/TopLevelManager/Tables/Branches/Components/data.tsx
  src/components/TopLevelManager/Tables/FoodItems/FoodItemList.tsx
  src/pages/TopLevelManager/Branches/ViewBranch.tsx
  src/types/branchStat.ts
Labels: enhancement

#129 fix: toggle button issue in home page
  src/pages/Home/index.tsx
Labels: enhancement, fix

#130 View food combos - Top level manager
  src/App.tsx
  src/api/useCombos.tsx
  src/components/TopLevelManager/Tables/FoodCombos/Components/ChevronDownIcon.tsx
  src/components/TopLevelManager/Tables/FoodCombos/Components/PlusIcon.tsx
  src/components/TopLevelManager/Tables/FoodCombos/Components/SearchIcon.tsx
  src/components/TopLevelManager/Tables/FoodCombos/Components/VerticalDotsIcon.tsx
  src/components/TopLevelManager/Tables/FoodCombos/Components/data.tsx
  src/components/TopLevelManager/Tables/FoodCombos/Components/types.tsx
  src/components/TopLevelManager/Tables/FoodCombos/FoodComboList.tsx
  src/components/TopLevelManager/Tables/FoodCombos/utils.ts
  src/pages/TopLevelManager/FoodCombos/Add.tsx
  src/pages/TopLevelManager/FoodCombos/Edit.tsx
  src/pages/TopLevelManager/FoodCombos/index.tsx
  src/types/combo.ts
Labels: enhancement, feat

#137 Top level manager
  src/images/logo/la-fresca.png
Labels: feat

#143 Complaint Management - Branch Manager
  src/App.tsx
  src/components/BranchManager/Sidebar/index.tsx
  src/components/BranchManager/Tables/Complaints/ComplainList.tsx
  src/components/BranchManager/Tables/Complaints/Components/ChevronDownIcon.tsx
  src/components/BranchManager/Tables/Complaints/Components/PlusIcon.tsx
  src/components/BranchManager/Tables/Complaints/Components/SearchIcon.tsx
  src/components/BranchManager/Tables/Complaints/Components/VerticalDotsIcon.tsx
  src/components/BranchManager/Tables/Complaints/Components/data.tsx
  src/components/BranchManager/Tables/Complaints/Components/types.tsx
  src/components/BranchManager/Tables/Complaints/utils.ts
  src/pages/BranchManager/Complaints/index.tsx
Labels: feat

#152 fix: Connect Discount Backend
  src/components/User/Discount/index.tsx
Labels: fix

#153 Branch Manager Inventory Management
  src/App.tsx
  src/components/BranchManager/Forms/Inventory/AddInventory.tsx
  src/components/BranchManager/Forms/Inventory/AddStock.tsx
  src/components/BranchManager/Forms/Inventory/EditInventory.tsx
  src/components/BranchManager/Forms/Inventory/EditStock.tsx
  src/components/BranchManager/Forms/Inventory/MultiCheckBox.tsx
  src/components/BranchManager/Sidebar/index.tsx
  src/components/BranchManager/Tables/Inventory/GrnList.tsx
  src/components/BranchManager/Tables/Inventory/GrnListbyCollection.tsx
  src/components/BranchManager/Tables/Inventory/InventoryList.tsx
  src/components/BranchManager/Tables/Inventory/columnInventory.ts
  src/components/BranchManager/Tables/Inventory/columnStocks.ts
  src/components/BranchManager/Tables/Inventory/stock/ChevronDownIcon.tsx
  src/components/BranchManager/Tables/Inventory/stock/PlusIcon.tsx
  src/components/BranchManager/Tables/Inventory/stock/SearchIcon.tsx
  src/components/BranchManager/Tables/Inventory/stock/VerticalDotsIcon.tsx
  src/components/BranchManager/Tables/Inventory/stock/data.tsx
  src/components/BranchManager/Tables/Inventory/stockCollection/ChevronDownIcon.tsx
  src/components/BranchManager/Tables/Inventory/stockCollection/PlusIcon.tsx
  src/components/BranchManager/Tables/Inventory/stockCollection/SearchIcon.tsx
  src/components/BranchManager/Tables/Inventory/stockCollection/VerticalDotsIcon.tsx
  src/components/BranchManager/Tables/Inventory/stockCollection/data.tsx
  src/components/BranchManager/Tables/Inventory/utils.ts
  src/pages/BranchManager/Inventory/AddGrn.tsx
  src/pages/BranchManager/Inventory/AddInventory.tsx
  src/pages/BranchManager/Inventory/EditGrn.tsx
  src/pages/BranchManager/Inventory/EditInventory.tsx
  src/pages/BranchManager/Inventory/GrnList.tsx
  src/pages/BranchManager/Inventory/GrnListByCollection.tsx
  src/pages/BranchManager/Inventory/InventoryList.tsx
Labels: feat

#154 Gallery UI
  package-lock.json
  package.json
  src/App.tsx
  src/pages/Home/SelectorIcon.tsx
  src/pages/Home/selectBranch.tsx
Labels: enhancement, feat

#155 Contact Us
  src/components/User/ContactUs/index.tsx
  src/components/User/Discount/index.tsx
Labels: feat, fix

#157 Contact Us
  package-lock.json
  src/App.tsx
  src/components/BranchManager/Complaint/index.tsx
  src/components/BranchManager/Header/DropdownUser.tsx
  src/components/BranchManager/Tables/Complaints/ComplainList.tsx
  src/components/Storekeeper/Tables/NextTables/InventoryList.tsx
  src/components/TopLevelManager/Tables/Branches/BranchList.tsx
  src/components/TopLevelManager/Tables/FoodItems/FoodItemList.tsx
  src/components/User/ContactUs/index.tsx
  src/pages/BranchManager/Complaints/view.tsx
Labels: fix

#158 fix: Customer SideNav
  src/components/User/Sidebar/index.tsx
  src/images/icon/cross-gray.png
  src/images/icon/cross-white.png
Labels: fix

#159 fix: Inventory management
  src/components/BranchManager/Tables/Inventory/GrnListbyCollection.tsx
  src/components/BranchManager/Tables/Inventory/InventoryList.tsx
  src/components/Storekeeper/Tables/NextTables/GrnListbyCollection.tsx
Labels: fix

#161 fix: inventory management for top-level manager
  src/components/TopLevelManager/Inventory/Tables/NextTables/InventoryList.tsx
  src/components/TopLevelManager/Stock/Tables/NextTables/InventoryList.tsx
  src/components/TopLevelManager/Tables/FoodItems/FoodItemList.tsx
  src/pages/TopLevelManager/Inventory/index.tsx
  src/pages/TopLevelManager/Stock/index.tsx
  src/types/stock.ts
Labels: fix
