Repository La-Fresca/la-fresca-frontend, pull requests merged in 2024-12, with the labels that each got.

#162 View delivery persons - kitchen manager
  package-lock.json
  src/App.tsx
  src/components/KitchenManager/Sidebar/index.tsx
  src/components/KitchenManager/Tables/DeliveryPerson/Components/ChevronDownIcon.tsx
  src/components/KitchenManager/Tables/DeliveryPerson/Components/PlusIcon.tsx
  src/components/KitchenManager/Tables/DeliveryPerson/Components/SearchIcon.tsx
  src/components/KitchenManager/Tables/DeliveryPerson/Components/VerticalDotsIcon.tsx
  src/components/KitchenManager/Tables/DeliveryPerson/Components/data.tsx
  src/components/KitchenManager/Tables/DeliveryPerson/Components/types.tsx
  src/components/KitchenManager/Tables/DeliveryPerson/DeliveryPerson.tsx
  src/components/KitchenManager/Tables/DeliveryPerson/utils.ts
  src/pages/KitchenManager/DeliveryPersons/index.tsx
Labels: feat

#163 Connect backend for view complaints - branch manager
  src/api/useComplaint.tsx
  src/components/BranchManager/Tables/Complaints/ComplainList.tsx
  src/components/BranchManager/Tables/Complaints/Components/data.tsx
  src/types/complaint.ts
Labels: fix

#165 feat: Waiters List for Kitchen Manager
  src/App.tsx
  src/components/KitchenManager/Sidebar/index.tsx
  src/components/KitchenManager/Tables/Waiter/Components/ChevronDownIcon.tsx
  src/components/KitchenManager/Tables/Waiter/Components/PlusIcon.tsx
  src/components/KitchenManager/Tables/Waiter/Components/SearchIcon.tsx
  src/components/KitchenManager/Tables/Waiter/Components/VerticalDotsIcon.tsx
  src/components/KitchenManager/Tables/Waiter/Components/data.tsx
  src/components/KitchenManager/Tables/Waiter/Components/types.tsx
  src/components/KitchenManager/Tables/Waiter/Waiter.tsx
  src/components/KitchenManager/Tables/Waiter/utils.ts
  src/pages/KitchenManager/Waiter/index.tsx
Labels: feat

#167 View all discounts for top-level manager
  src/components/TopLevelManager/Tables/Discounts/Components/data.tsx
  src/components/TopLevelManager/Tables/Discounts/DiscountList.tsx
  src/types/discount.ts
Labels: fix

#168 User Management for Branch Manager
  src/components/BranchManager/Tables/UserManagement/AddUser.tsx
  src/components/BranchManager/Tables/UserManagement/Components/ChevronDownIcon.tsx
  src/components/BranchManager/Tables/UserManagement/Components/PlusIcon.tsx
  src/components/BranchManager/Tables/UserManagement/Components/SearchIcon.tsx
  src/components/BranchManager/Tables/UserManagement/Components/VerticalDotsIcon.tsx
  src/components/BranchManager/Tables/UserManagement/Components/data.tsx
  src/components/BranchManager/Tables/UserManagement/EditUser.tsx
  src/components/BranchManager/Tables/UserManagement/UsersList.tsx
  src/components/BranchManager/Tables/UserManagement/utils.ts
  src/components/BranchManager/UserManagement/Button.tsx
  src/components/BranchManager/UserManagement/UserRow.tsx
  src/components/BranchManager/UserManagement/UserTable.tsx
  src/pages/BranchManager/Users/AddUser.tsx
  src/pages/BranchManager/Users/EditUser.tsx
  src/pages/BranchManager/Users/index.tsx
Labels: fix

#169 Branch Manager List for Top-level Manager
  src/App.tsx
  src/api/useUser.tsx
  src/components/TopLevelManager/Sidebar/index.tsx
  src/components/TopLevelManager/Tables/BranchManagerManagement/AddBranchManager.tsx
  src/components/TopLevelManager/Tables/BranchManagerManagement/BranchManagerList.tsx
  src/components/TopLevelManager/Tables/BranchManagerManagement/Components/ChevronDownIcon.tsx
  src/components/TopLevelManager/Tables/BranchManagerManagement/Components/PlusIcon.tsx
  src/components/TopLevelManager/Tables/BranchManagerManagement/Components/SearchIcon.tsx
  src/components/TopLevelManager/Tables/BranchManagerManagement/Components/VerticalDotsIcon.tsx
  src/components/TopLevelManager/Tables/BranchManagerManagement/Components/data.tsx
  src/components/TopLevelManager/Tables/BranchManagerManagement/EditBranchManager.tsx
  src/components/TopLevelManager/Tables/BranchManagerManagement/utils.ts
  src/pages/TopLevelManager/BrancheManager/AddBranchManager.tsx
  src/pages/TopLevelManager/BrancheManager/EditBranchManager.tsx
  src/pages/TopLevelManager/BrancheManager/index.tsx
  src/types/branch.ts
Labels: feat, fix

#170 Delivery Person Order queue connected
  public/gallery-img/1.avif
  public/gallery-img/10.avif
  public/gallery-img/11.avif
  public/gallery-img/12.avif
  public/gallery-img/13.avif
  public/gallery-img/14.avif
  public/gallery-img/15.avif
  public/gallery-img/16.avif
  public/gallery-img/17.avif
  public/gallery-img/18.avif
  public/gallery-img/19.avif
  public/gallery-img/2.avif
  public/gallery-img/20.avif
  public/gallery-img/3.avif
  public/gallery-img/4.avif
  public/gallery-img/5.avif
  public/gallery-img/6.avif
  public/gallery-img/7.avif
  public/gallery-img/8.avif
  public/gallery-img/9.avif
  src/api/useDelivery.tsx
  src/api/useOrder.tsx
  src/components/Landing/Menus.tsx
  src/components/Landing/images-slider.tsx
  src/components/User/ContactUs/index.tsx
  src/pages/DeliveryPerson/History.tsx
  src/pages/DeliveryPerson/Home.tsx
  src/pages/DeliveryPerson/OrderCard.tsx
  src/pages/DeliveryPerson/OrderQueue.tsx
  src/pages/Home/index.tsx
  src/types/order.ts
Labels: feat
